-- Canonical, provider-independent operational records. UUIDs are generated by
-- the application. All timestamps are TIMESTAMPTZ UTC instants; PostgreSQL
-- stores the instant independently of the session display timezone.

CREATE TABLE operators (
    id UUID PRIMARY KEY,
    code TEXT NOT NULL UNIQUE CHECK (code <> ''),
    display_name TEXT NOT NULL CHECK (display_name <> ''),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE provider_envelopes (
    id UUID PRIMARY KEY,
    operator_id UUID NOT NULL REFERENCES operators(id),
    schema_version SMALLINT NOT NULL CHECK (schema_version > 0),
    provider TEXT NOT NULL CHECK (provider <> ''),
    feed TEXT NOT NULL CHECK (feed <> ''),
    provider_record_id TEXT,
    event_time TIMESTAMPTZ,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ,
    raw_payload_sha256 TEXT NOT NULL CHECK (raw_payload_sha256 ~ '^[0-9a-f]{64}$'),
    raw_payload JSONB NOT NULL,
    UNIQUE (operator_id, id),
    CHECK (processed_at IS NULL OR processed_at >= received_at)
);

CREATE UNIQUE INDEX provider_envelopes_provider_record_unique
    ON provider_envelopes (operator_id, provider, feed, provider_record_id)
    WHERE provider_record_id IS NOT NULL;
CREATE INDEX provider_envelopes_received_at_idx
    ON provider_envelopes (operator_id, received_at DESC);

CREATE TABLE flights (
    id UUID PRIMARY KEY,
    operator_id UUID NOT NULL REFERENCES operators(id),
    source_envelope_id UUID NOT NULL,
    schema_version SMALLINT NOT NULL CHECK (schema_version > 0),
    event_time TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    callsign TEXT,
    aircraft_registration TEXT,
    origin_airport_code TEXT,
    destination_airport_code TEXT,
    scheduled_departure_at TIMESTAMPTZ,
    scheduled_arrival_at TIMESTAMPTZ,
    status TEXT NOT NULL CHECK (
        status IN ('scheduled', 'active', 'diverted', 'landed', 'cancelled', 'unknown')
    ),
    UNIQUE (operator_id, id),
    FOREIGN KEY (operator_id, source_envelope_id)
        REFERENCES provider_envelopes(operator_id, id),
    CHECK (processed_at >= received_at),
    CHECK (
        scheduled_arrival_at IS NULL
        OR scheduled_departure_at IS NULL
        OR scheduled_arrival_at >= scheduled_departure_at
    )
);

CREATE INDEX flights_operator_status_idx ON flights (operator_id, status);
CREATE INDEX flights_source_envelope_idx ON flights (operator_id, source_envelope_id);

CREATE TABLE aircraft_positions (
    id UUID PRIMARY KEY,
    operator_id UUID NOT NULL REFERENCES operators(id),
    flight_id UUID NOT NULL,
    source_envelope_id UUID NOT NULL,
    schema_version SMALLINT NOT NULL CHECK (schema_version > 0),
    event_time TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    position GEOMETRY(POINT, 4326) NOT NULL,
    altitude_value INTEGER,
    altitude_unit TEXT,
    altitude_reference TEXT,
    heading_true_degrees DOUBLE PRECISION CHECK (
        heading_true_degrees >= 0 AND heading_true_degrees < 360
    ),
    ground_speed_value DOUBLE PRECISION CHECK (ground_speed_value >= 0),
    ground_speed_unit TEXT,
    source_quality TEXT NOT NULL CHECK (
        source_quality IN ('observed', 'fused', 'estimated', 'unknown')
    ),
    UNIQUE (operator_id, id),
    FOREIGN KEY (operator_id, flight_id) REFERENCES flights(operator_id, id),
    FOREIGN KEY (operator_id, source_envelope_id)
        REFERENCES provider_envelopes(operator_id, id),
    CHECK (processed_at >= received_at),
    CHECK (ST_X(position) BETWEEN -180 AND 180),
    CHECK (ST_Y(position) BETWEEN -90 AND 90),
    CHECK (
        (altitude_value IS NULL AND altitude_unit IS NULL AND altitude_reference IS NULL)
        OR (
            altitude_value IS NOT NULL
            AND altitude_unit IN ('feet', 'meters')
            AND altitude_reference IN (
                'mean_sea_level', 'above_ground_level', 'flight_level', 'ellipsoid'
            )
        )
    ),
    CHECK (
        (ground_speed_value IS NULL AND ground_speed_unit IS NULL)
        OR (
            ground_speed_value IS NOT NULL
            AND ground_speed_unit IN ('knots', 'kilometers_per_hour')
        )
    )
);

CREATE INDEX aircraft_positions_flight_time_idx
    ON aircraft_positions (operator_id, flight_id, event_time DESC);
CREATE INDEX aircraft_positions_position_gist_idx
    ON aircraft_positions USING GIST (position);

CREATE TABLE planned_routes (
    id UUID PRIMARY KEY,
    operator_id UUID NOT NULL REFERENCES operators(id),
    flight_id UUID NOT NULL,
    source_envelope_id UUID NOT NULL,
    schema_version SMALLINT NOT NULL CHECK (schema_version > 0),
    event_time TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    route_version INTEGER NOT NULL CHECK (route_version > 0),
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ,
    path GEOMETRY(LINESTRING, 4326) NOT NULL,
    UNIQUE (operator_id, id),
    UNIQUE (operator_id, flight_id, route_version),
    FOREIGN KEY (operator_id, flight_id) REFERENCES flights(operator_id, id),
    FOREIGN KEY (operator_id, source_envelope_id)
        REFERENCES provider_envelopes(operator_id, id),
    CHECK (processed_at >= received_at),
    CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE INDEX planned_routes_path_gist_idx ON planned_routes USING GIST (path);

CREATE TABLE weather_hazards (
    id UUID PRIMARY KEY,
    operator_id UUID NOT NULL REFERENCES operators(id),
    source_envelope_id UUID NOT NULL,
    schema_version SMALLINT NOT NULL CHECK (schema_version > 0),
    event_time TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    hazard_type TEXT NOT NULL CHECK (hazard_type <> ''),
    severity TEXT NOT NULL CHECK (
        severity IN ('advisory', 'significant', 'severe', 'unknown')
    ),
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ NOT NULL,
    altitude_lower_value INTEGER,
    altitude_lower_unit TEXT,
    altitude_lower_reference TEXT,
    altitude_upper_value INTEGER,
    altitude_upper_unit TEXT,
    altitude_upper_reference TEXT,
    footprint GEOMETRY(POLYGON, 4326) NOT NULL,
    UNIQUE (operator_id, id),
    FOREIGN KEY (operator_id, source_envelope_id)
        REFERENCES provider_envelopes(operator_id, id),
    CHECK (processed_at >= received_at),
    CHECK (valid_to >= valid_from),
    CHECK (
        (altitude_lower_value IS NULL AND altitude_lower_unit IS NULL AND altitude_lower_reference IS NULL)
        OR (
            altitude_lower_value IS NOT NULL
            AND altitude_lower_unit IN ('feet', 'meters')
            AND altitude_lower_reference IN (
                'mean_sea_level', 'above_ground_level', 'flight_level', 'ellipsoid'
            )
        )
    ),
    CHECK (
        (altitude_upper_value IS NULL AND altitude_upper_unit IS NULL AND altitude_upper_reference IS NULL)
        OR (
            altitude_upper_value IS NOT NULL
            AND altitude_upper_unit IN ('feet', 'meters')
            AND altitude_upper_reference IN (
                'mean_sea_level', 'above_ground_level', 'flight_level', 'ellipsoid'
            )
        )
    )
);

CREATE INDEX weather_hazards_validity_idx
    ON weather_hazards (operator_id, valid_from, valid_to);
CREATE INDEX weather_hazards_footprint_gist_idx
    ON weather_hazards USING GIST (footprint);

CREATE TABLE alerts (
    id UUID PRIMARY KEY,
    operator_id UUID NOT NULL REFERENCES operators(id),
    schema_version SMALLINT NOT NULL CHECK (schema_version > 0),
    event_time TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    flight_id UUID,
    hazard_id UUID,
    alert_type TEXT NOT NULL CHECK (alert_type <> ''),
    severity TEXT NOT NULL CHECK (
        severity IN ('information', 'advisory', 'warning', 'critical')
    ),
    lifecycle TEXT NOT NULL CHECK (
        lifecycle IN ('open', 'acknowledged', 'dismissed', 'resolved')
    ),
    rule_id TEXT NOT NULL CHECK (rule_id <> ''),
    rule_version INTEGER NOT NULL CHECK (rule_version > 0),
    dedupe_key TEXT NOT NULL CHECK (dedupe_key <> ''),
    UNIQUE (operator_id, id),
    UNIQUE (operator_id, dedupe_key),
    FOREIGN KEY (operator_id, flight_id) REFERENCES flights(operator_id, id),
    FOREIGN KEY (operator_id, hazard_id) REFERENCES weather_hazards(operator_id, id),
    CHECK (processed_at >= received_at)
);

CREATE INDEX alerts_lifecycle_severity_idx
    ON alerts (operator_id, lifecycle, severity, event_time DESC);

CREATE TABLE alert_evidence (
    operator_id UUID NOT NULL REFERENCES operators(id),
    alert_id UUID NOT NULL,
    source_envelope_id UUID NOT NULL,
    ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
    PRIMARY KEY (operator_id, alert_id, source_envelope_id),
    UNIQUE (operator_id, alert_id, ordinal),
    FOREIGN KEY (operator_id, alert_id) REFERENCES alerts(operator_id, id),
    FOREIGN KEY (operator_id, source_envelope_id)
        REFERENCES provider_envelopes(operator_id, id)
);

CREATE TABLE alert_actions (
    id UUID PRIMARY KEY,
    operator_id UUID NOT NULL REFERENCES operators(id),
    alert_id UUID NOT NULL,
    schema_version SMALLINT NOT NULL CHECK (schema_version > 0),
    action TEXT NOT NULL CHECK (
        action IN ('acknowledge', 'dismiss', 'comment', 'resolve')
    ),
    actor_id TEXT NOT NULL CHECK (actor_id <> ''),
    occurred_at TIMESTAMPTZ NOT NULL,
    comment TEXT,
    UNIQUE (operator_id, id),
    FOREIGN KEY (operator_id, alert_id) REFERENCES alerts(operator_id, id)
);

CREATE INDEX alert_actions_alert_time_idx
    ON alert_actions (operator_id, alert_id, occurred_at);

CREATE TABLE source_health (
    id UUID PRIMARY KEY,
    operator_id UUID NOT NULL REFERENCES operators(id),
    schema_version SMALLINT NOT NULL CHECK (schema_version > 0),
    provider TEXT NOT NULL CHECK (provider <> ''),
    feed TEXT NOT NULL CHECK (feed <> ''),
    state TEXT NOT NULL CHECK (
        state IN ('healthy', 'degraded', 'stale', 'unavailable', 'unknown')
    ),
    observed_at TIMESTAMPTZ NOT NULL,
    last_success_at TIMESTAMPTZ,
    delay_seconds BIGINT CHECK (delay_seconds >= 0),
    stale_after_seconds BIGINT NOT NULL CHECK (stale_after_seconds > 0),
    last_error_code TEXT,
    UNIQUE (operator_id, id),
    UNIQUE (operator_id, provider, feed)
);

COMMENT ON COLUMN aircraft_positions.position IS
    'WGS84 EPSG:4326 point; PostGIS/GeoJSON order is longitude then latitude.';
COMMENT ON COLUMN aircraft_positions.heading_true_degrees IS
    'True heading in degrees in the half-open range [0, 360).';
COMMENT ON COLUMN provider_envelopes.event_time IS
    'Provider event time when supplied; null means the provider did not supply one.';
COMMENT ON COLUMN provider_envelopes.received_at IS
    'UTC instant when this system accepted the raw record.';
COMMENT ON COLUMN provider_envelopes.processed_at IS
    'UTC instant when normalization completed; null while unprocessed or failed.';
